#pragma once

#include <px4_platform_common/px4_config.h>
#include <nuttx/compiler.h>
#include <stdint.h>

/* MatekSys F405 Pin Mappings */

/* SPI1 - IMU & OSD */
#undef GPIO_SPI1_SCK
#undef GPIO_SPI1_MISO
#undef GPIO_SPI1_MOSI
#define GPIO_SPI1_SCK	(GPIO_SPI1_SCK_1|GPIO_SPEED_50MHz)
#define GPIO_SPI1_MISO	(GPIO_SPI1_MISO_1|GPIO_SPEED_50MHz)
#define GPIO_SPI1_MOSI	(GPIO_SPI1_MOSI_1|GPIO_SPEED_50MHz)

/* SPI2 */
#undef GPIO_SPI2_SCK
#undef GPIO_SPI2_MISO
#undef GPIO_SPI2_MOSI
#define GPIO_SPI2_SCK	(GPIO_SPI2_SCK_1|GPIO_SPEED_50MHz)
#define GPIO_SPI2_MISO	(GPIO_SPI2_MISO_1|GPIO_SPEED_50MHz)
#define GPIO_SPI2_MOSI	(GPIO_SPI2_MOSI_1|GPIO_SPEED_50MHz)

/* I2C1 - Baro */
#undef GPIO_I2C1_SCL
#undef GPIO_I2C1_SDA
#define GPIO_I2C1_SCL	(GPIO_I2C1_SCL_1|GPIO_SPEED_50MHz)
#define GPIO_I2C1_SDA	(GPIO_I2C1_SDA_1|GPIO_SPEED_50MHz)

/* UARTs */
#undef GPIO_USART1_TX
#undef GPIO_USART1_RX
#undef GPIO_USART2_TX
#undef GPIO_USART2_RX
#undef GPIO_USART3_TX
#undef GPIO_USART3_RX
#undef GPIO_UART4_TX
#undef GPIO_UART4_RX
#undef GPIO_UART5_TX
#undef GPIO_UART5_RX
#define GPIO_USART1_TX	(GPIO_USART1_TX_1|GPIO_SPEED_50MHz)
#define GPIO_USART1_RX	(GPIO_USART1_RX_1|GPIO_SPEED_50MHz)
#define GPIO_USART2_TX	(GPIO_USART2_TX_1|GPIO_SPEED_50MHz)
#define GPIO_USART2_RX	(GPIO_USART2_RX_1|GPIO_SPEED_50MHz)
#define GPIO_USART3_TX	(GPIO_USART3_TX_1|GPIO_SPEED_50MHz)
#define GPIO_USART3_RX	(GPIO_USART3_RX_1|GPIO_SPEED_50MHz)
#define GPIO_UART4_TX	(GPIO_UART4_TX_1|GPIO_SPEED_50MHz)
#define GPIO_UART4_RX	(GPIO_UART4_RX_1|GPIO_SPEED_50MHz)
#define GPIO_UART5_TX	(GPIO_UART5_TX_1|GPIO_SPEED_50MHz)
#define GPIO_UART5_RX	(GPIO_UART5_RX_1|GPIO_SPEED_50MHz)

/* USB VCP */
#undef GPIO_OTGFS_VBUS
#undef GPIO_OTGFS_DM
#undef GPIO_OTGFS_DP
#define GPIO_OTGFS_VBUS		(GPIO_PORTA|GPIO_PIN9|GPIO_INPUT|GPIO_FLOAT)
#define GPIO_OTGFS_DM		(GPIO_PORTA|GPIO_PIN11|GPIO_ALT|GPIO_PULLUP|GPIO_SPEED_100MHz|GPIO_AF10_OTG_FS)
#define GPIO_OTGFS_DP		(GPIO_PORTA|GPIO_PIN12|GPIO_ALT|GPIO_PULLUP|GPIO_SPEED_100MHz|GPIO_AF10_OTG_FS)

/* SDIO */
#undef GPIO_SDIO_D0
#undef GPIO_SDIO_D1
#undef GPIO_SDIO_D2
#undef GPIO_SDIO_D3
#undef GPIO_SDIO_CK
#undef GPIO_SDIO_CMD
#define GPIO_SDIO_D0		(GPIO_PORTC|GPIO_PIN8|GPIO_ALT|GPIO_PULLUP|GPIO_SPEED_50MHz|GPIO_AF12_SDIO)
#define GPIO_SDIO_D1		(GPIO_PORTC|GPIO_PIN9|GPIO_ALT|GPIO_PULLUP|GPIO_SPEED_50MHz|GPIO_AF12_SDIO)
#define GPIO_SDIO_D2		(GPIO_PORTC|GPIO_PIN10|GPIO_ALT|GPIO_PULLUP|GPIO_SPEED_50MHz|GPIO_AF12_SDIO)
#define GPIO_SDIO_D3		(GPIO_PORTC|GPIO_PIN11|GPIO_ALT|GPIO_PULLUP|GPIO_SPEED_50MHz|GPIO_AF12_SDIO)
#define GPIO_SDIO_CK		(GPIO_PORTC|GPIO_PIN12|GPIO_ALT|GPIO_PULLUP|GPIO_SPEED_50MHz|GPIO_AF12_SDIO)
#define GPIO_SDIO_CMD		(GPIO_PORTD|GPIO_PIN2|GPIO_ALT|GPIO_PULLUP|GPIO_SPEED_50MHz|GPIO_AF12_SDIO)

/* LED - PB5, active low */
#define GPIO_LED_BLUE  (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|GPIO_OUTPUT_SET|GPIO_PORTB|GPIO_PIN5)
#define GPIO_LED1       GPIO_LED_BLUE
#define BOARD_OVERLOAD_LED     LED_BLUE

/* DMA pool */
#define BOARD_DMA_ALLOC_POOL_SIZE 5120

/* PWM OUT */
#define DIRECT_PWM_OUTPUT_CHANNELS  8
#define DIRECT_FMU_PWM_CHANNELS     8

/* ADC - Battery voltage/current on PC2/PC3 */
#define ADC_CHANNELS \
	((1 << 12) | (1 << 13))   /* PC2 = ADC12_IN12, PC3 = ADC12_IN13 */
#define ADC_BATTERY_VOLTAGE_CHANNEL  12
#define ADC_BATTERY_CURRENT_CHANNEL  13

/* High-resolution timer - TIM8 CH1 (APB2, exclusive use) */
#define HRT_TIMER                    8
#define HRT_TIMER_CHANNEL            1
#define HRT_PPM_CHANNEL              3
#define GPIO_PPM_IN                  (GPIO_ALT|GPIO_AF2|GPIO_PULLUP|GPIO_PORTB|GPIO_PIN8)

/* RC serial port */
#define RC_SERIAL_PORT               "/dev/ttyS0"
#define BOARD_SUPPORTS_RC_SERIAL_PORT_OUTPUT

/* Console buffer for dmesg */
#define BOARD_ENABLE_CONSOLE_BUFFER
#define BOARD_CONSOLE_BUFFER_SIZE (1024*2)

/* Store params in flash (no EEPROM/MTD on this board) */
#define FLASH_BASED_PARAMS

/* Bootloader / LED pins */
#define BOARD_HAS_BOOTDELAY 0

#include <px4_platform_common/board_common.h>
